### ISSUE TITLE
General: All team members install IDE and appropriate software

### ISSUE THREAD

**Issue by BenKenobi24** [asu-cis-capstone/boulders#4]

**Comment by ghost** [comment]
We are using MEAN stack. This means to contribute any code to the website, you need nodeJS, and MongoDB installed on your computers. Front-end website is done in AngularJS with Bootstrap.....The andriod app is going to be done in JS too using React Native. Not a bad time to review some JavaScript ;).

**Comment by ghost** [comment]
one language to rule them all!
